### ISSUE TITLE
Wrap it with docker

### ISSUE THREAD

**Issue by vitonsky** [frectonz/sql-studio#3]
Hi, it is good idea to wrap your code with docker container, to let world to try your solution.

The instructions for a docker is a modern standard of distribution for a web software.

It's pretty hard to build all the thing on my PC to just see every solution on the github, so me and lot of another people will just skip a repo with instructions "how to build" and with no instructions "how to run right here right now with docker".

**Comment by frectonz** [comment]
We do have a pre built binaries available on the [releases page](https://github.com/frectonz/sqlite-studio/releases).

We also have a version on [Docker Hub](https://hub.docker.com/r/frectonz/sqlite-studio) but that docker image only allows you to view a sample database. It doesn't allow you to configure your own sqlite database. We will add feature soon.

**Comment by eznix86** [comment]
Maybe, what you can do is that, you check the if there is a sqlite in a specific folder. Example you have `/database` folder in the project. if the the rust code find a .db file inside it will load it. It allows anyone to create a volume to this folder.

**Comment by Cufee** [comment]
It is really useful to debug things sometimes for sure. I am running this on my node alongside Tailscale, works great
```yaml
services:
  sqlite-studio:
    image: frectonz/sqlite-studio:0.1.8
    command: /nix/store/84b16i4lzii52bzbdggf5b17qsarp00p-sqlite-studio-0.1.8/bin/sqlite-studio --address=0.0.0.0:3030 sqlite /mounted/${DATABASE_NAME}
    volumes:
      - ${DATABASE_PATH}:/mounted
```
