### ISSUE TITLE
Add support for local libsql files

### ISSUE THREAD

**Issue by YourTechBud** [frectonz/sql-studio#51]
I've been using the open source version of libsql as an embedded database as opposed to running it as a separate process.

Can we add support for this usecase as well. Here's a reference to how we can do this in Rust: https://docs.turso.tech/sdk/rust/reference#local-development

**Comment by frectonz** [comment]
Will you open a PR for this?

**Comment by YourTechBud** [comment]
I can try.

**Comment by frectonz** [comment]
This has been implemented in `0.1.32`. You can use the following command to open a sqlite file with the libSQL driver.

```
sql-studio local-libsql [database]
```

**Comment by MostHated** [comment]
I am attempting to run both of these in docker via compose, but not having luck with libsql, local-libsql. Is there a specific way that this should be done that I have missed?

<details>
<summary>docker-compose.yml</summary>

```yaml
version: "3"
services:
  # --| LibSQL Database ----------
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - "9080:8080"
      - "5001:5001"
    environment:
      - SQLD_NODE=primary
      - SQLD_HTTP_LISTEN_ADDR=0.0.0.0:8080
    volumes:
      - ./data/libsql:/var/lib/sqld
    networks:
      - libsql-network

  # --| SQL Studio ---------------
  sql-studio:
      image: frectonz/sql-studio
      ports:
          - "3030:3030"
      volumes:
        - ./data:/db
      command:
          /bin/sql-studio --no-browser --no-shutdown --address=0.0.0.0:3030 # See below for options tried 

        # libsql http://db:8080
        # Errors because no auth token

        # local-libsql /data/libsql/iku.db
        # 0: Failed to connect to database: `Unable to open connection to local database /data/libsql/iku.db: 14`

        # local-libsql http://db:8080
        # Failed to connect to database: `Unable to open local database http://db:8080 with Database::open()
      networks:
          - libsql-network
      depends_on:
          - db

networks:
  libsql-network:
    name: libsql-network
```

</details>
