### ISSUE TITLE
Docker support for both libsql and sqlstudio

### ISSUE THREAD

**Issue by MostHated** [frectonz/sql-studio#52]
I am attempting to run both of these in docker via compose (not sure if it is a supported configuration?), but not having luck with libsql or local-libsql. Is there currently a way in which this can be accomplished?

```yaml
version: "3"
services:
  # --| LibSQL Database ----------
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - "9080:8080"
      - "5001:5001"
    environment:
      - SQLD_NODE=primary
      - SQLD_HTTP_LISTEN_ADDR=0.0.0.0:8080
    volumes:
      - ./data/libsql:/var/lib/sqld
    networks:
      - libsql-network

  # --| SQL Studio ---------------
  sql-studio:
      image: frectonz/sql-studio
      ports:
          - "3030:3030"
      volumes:
        - ./data:/db
      command: # Tried with and without the --no-browser flag, just in case
          /bin/sql-studio --no-browser --no-shutdown --address=0.0.0.0:3030 # See below for options tried 

        # libsql (http://db:8080 | libsql://db:5001)
        # Errors because no auth token

        # local-libsql /db/libsql/iku.db
        # 0: Failed to connect to database: `Unable to open connection to local database /db/libsql/iku.db: 14`

        # local-libsql http://db:8080
        # Failed to connect to database: `Unable to open local database http://db:8080 with Database::open()

        # local-libsql libsql://db:5001
        # 0: Failed to connect to database: `Unable to open local database libsql://db:5001 with Database::open()`
      networks:
          - libsql-network
      depends_on:
          - db

networks:
  libsql-network:
    name: libsql-network
```
