### ISSUE TITLE
sqlite: No such file or directory

### ISSUE THREAD

**Issue by jaskierrr** [frectonz/sql-studio#56]
docker image does not see the file sqlite DB

logs: 
`2025-01-02T17:45:01.981011Z  INFO sql_studio::sqlite: found 1 tables in data/test_db.sqlite3`
`2025-01-02T17:45:01.982106Z  INFO sql_studio: tried to open in browser: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })`

docker-compose: 
```
services:
  music-lib-py:
    container_name: music_app_py
    image: music_app_py
    deploy:
      restart_policy:
        condition: no
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - .:/app

  sqlite-studio:
    container_name: music_py_sqlite-studio
    image: frectonz/sql-studio
    ports:
      - "3030:3030"
    command: ["sql-studio", "sqlite", "data/test_db.sqlite3"]
    volumes:
      - ./data:/data

volumes:
 data:
```

but everything works through PowerShell, I mean the file is good

I'm new to docker and I can't figure out what the problem is.
